# Use root/example as user/password credentials
version: '3.1'

services:
  db_amazon_store:
    image: mysql:5.7
    container_name: mysql_amazon_store
    security_opt:
      - seccomp:unconfined
    ports:
      - '3307:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_DATABASE: amazon_store
      MYSQL_USER: amazon_store
      MYSQL_PASSWORD: secret_password

